name: basecode
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  lottie: ^3.1.2
  firebase_auth: ^5.1.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  icons_flutter: ^0.0.4
  image_picker: ^1.1.2
  provider: ^6.1.2
  change_app_package_name: ^1.5.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  csv: ^6.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
